[pytest]

markers =
    smoke: Critical tests for quick validation
    regression: Full regression test suite
    negative: Negative and error handling tests
    wlan: All wlan related tests

testpaths = tests