[pytest]

markers =
    smoke: Critical tests for quick validation
    regression: Full regression test suite
    negative: Negative and error handling tests
    wlan: All wlan related tests

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    --html=/app/reports/wlan_test_report.html 
    --self-contained-html
    --junitxml=/app/reports/junit-results.xml
    -v