apiVersion: batch/v1
kind: Job
metadata:
  name: wifi-pytest-job
  labels:
    app: wifi-pytest
spec:
  # Do NOT include ttlSecondsAfterFinished here so pod persists for report extraction
  template:
    metadata:
      labels:
        app: wifi-pytest
    spec:
      restartPolicy: Never
      containers:
        - name: wifi-pytest-container
          image: wifi-pytest-advanced:1.0
          volumeMounts:
            - mountPath: /app/reports
              name: reports-vol
      volumes:
        - name: reports-vol
          persistentVolumeClaim:
            claimName: wifi-pytest-reports-pvc